services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: ["npx", "nodemon", "src/app.js"]
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html

volumes:
  mongo_data: